plugins {
    id 'java'
    id("xyz.jpenilla.run-paper") version "3.0.2"
    id 'io.papermc.paperweight.userdev' version '2.0.0-beta.21'
}

group = 'com.github.darksoulq'
version = '1.0.0-mc.26.1.2'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        url = uri("https://jitpack.io/")
    }
    maven {
        name = "faststatsReleases"
        url = uri("https://repo.faststats.dev/releases")
    }
}

dependencies {
    paperweight.paperDevBundle('26.1.2.build.12-alpha')
    implementation("com.github.darksoulq:AbyssalLib:v2.0.5-mc.26.1.2")
    compileOnly('com.fasterxml.jackson.core:jackson-databind:2.17.0')
    compileOnly('com.fasterxml.jackson.core:jackson-core:2.17.0')
    implementation("dev.faststats.metrics:bukkit:0.22.0")
}

tasks {
    runServer {
        minecraftVersion("26.1.2")
    }
}

def targetJavaVersion = 25
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withJavadocJar()
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

javadoc {
    options.encoding = 'UTF-8'
    options.charSet = 'UTF-8'
    options.memberLevel = JavadocMemberLevel.PUBLIC
    options.author = true
    options.version = true
    options.links('https://docs.oracle.com/en/java/javase/21/docs/api/')
}

artifacts {
    archives(sourcesJar)
    archives(javadocJar)
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('paper-plugin.yml') {
        expand props
    }
}
