name: Relique
version: '2.1.2-mc.26.1.2'
main: com.github.darksoulq.relique.Relique
api-version: '26.1'

folia-supported: true

dependencies:
  server:
    AbyssalLib:
      required: true
      load: BEFORE