name: Relique
version: '${version}'
main: com.github.darksoulq.relique.Relique
api-version: '${apiVersion}'

folia-supported: true

dependencies:
  server:
    AbyssalLib:
      required: true
      load: BEFORE